import { readFile, writeFile, batchCommit, FileChange } from "./file-store";
import matter from "gray-matter";

export interface IndexEntry {
  title: string;
  relPath: string;
  description: string;
  type: string;
}

/**
 * Read an index file from the repository.
 */
export async function readIndex(
  indexRelPath: string,
): Promise<string | null> {
  return readFile(indexRelPath);
}

/**
 * Write an index file to the repository.
 */
export async function writeIndex(
  indexRelPath: string,
  content: string,
): Promise<void> {
  await writeFile(indexRelPath, content, `Update index: ${indexRelPath}`);
}

/**
 * Rebuild all index.md files from the current file list.
 * Returns list of changed index paths.
 */
export async function rebuildAllIndexes(
  files: Array<{
    relPath: string;
    frontmatter: Record<string, any>;
  }>,
): Promise<string[]> {
  const timestamp = new Date().toISOString();
  const changes: FileChange[] = [];
  const changedPaths: string[] = [];

  // Filter out index and log files
  const assetFiles = files.filter(
    (f) =>
      !f.relPath.endsWith("/index") &&
      f.relPath !== "index" &&
      f.relPath !== "log",
  );

  // Group by top-level folder
  const topLevelFolders = new Set<string>();
  assetFiles.forEach((f) => {
    const parts = f.relPath.split("/");
    if (parts.length > 1) {
      topLevelFolders.add(parts[0]);
    }
  });

  // Group by type for master index
  const categories: Record<string, IndexEntry[]> = {};
  assetFiles.forEach((f) => {
    const typeKey = f.frontmatter.type || "Uncategorized";
    if (!categories[typeKey]) categories[typeKey] = [];
    categories[typeKey].push({
      title: f.frontmatter.title || f.relPath.split("/").pop() || "",
      relPath: f.relPath,
      description:
        f.frontmatter.description || "No descriptive overview available.",
      type: typeKey,
    });
  });

  // Generate subfolder index files
  for (const topFolder of topLevelFolders) {
    const folderFiles = assetFiles.filter((f) =>
      f.relPath.startsWith(`${topFolder}/`),
    );

    const folderNameFormatted =
      topFolder.charAt(0).toUpperCase() + topFolder.slice(1);

    let subIndexContent = `---
type: CategoryIndex
category: ${folderNameFormatted}
title: ${folderNameFormatted} Domain Operational Map
description: Local category index for ${topFolder} domain assets.
timestamp: ${timestamp}
---
# ${folderNameFormatted} Domain Operational Map

This index outlines all knowledge nodes registered within the ${topFolder} domain.

`;

    folderFiles.forEach((f) => {
      const relToFolder = f.relPath.substring(topFolder.length + 1);
      const title = f.frontmatter.title || f.relPath.split("/").pop() || "";
      const description =
        f.frontmatter.description || "No descriptive overview available.";
      subIndexContent += `* [${title}](./${relToFolder}) - ${description}\n`;
    });

    const indexPath = `${topFolder}/index`;
    changes.push({ path: indexPath, content: subIndexContent.trim() + "\n" });
    changedPaths.push(indexPath);
  }

  // Generate master root index
  let masterIndexContent = `---
type: Index
title: Central Operational Registry Map
description: Autogenerated progressive disclosure map grouping active supply chain category indexes and node vectors.
timestamp: ${timestamp}
---
# Central Operational Registry Map

This master index profiles active framework directory category indexes and registered asset nodes.

## Subfolder Category Indexes

`;

  Array.from(topLevelFolders)
    .sort()
    .forEach((topFolder) => {
      const folderNameFormatted =
        topFolder.charAt(0).toUpperCase() + topFolder.slice(1);
      const count = assetFiles.filter((f) =>
        f.relPath.startsWith(`${topFolder}/`),
      ).length;
      masterIndexContent += `* [${folderNameFormatted} Category Index](./${topFolder}/index.md) - Subfolder operational map containing ${count} asset(s)\n`;
    });

  masterIndexContent += `\n## Registered Asset Nodes\n\n`;

  Object.keys(categories)
    .sort()
    .forEach((category) => {
      masterIndexContent += `### ${category}\n`;
      categories[category]
        .sort((a, b) => a.title.localeCompare(b.title))
        .forEach((item) => {
          masterIndexContent += `* [${item.title}](./${item.relPath}.md) - ${item.description}\n`;
        });
      masterIndexContent += `\n`;
    });

  changes.push({ path: "index", content: masterIndexContent.trim() + "\n" });
  changedPaths.push("index");

  // Batch commit all index changes
  if (changes.length > 0) {
    await batchCommit(changes, [], "Rebuild index files");
  }

  return changedPaths;
}

/**
 * Append an entry to the log.md file.
 */
export async function appendToLog(entry: string): Promise<void> {
  const existing = (await readFile("log")) || "";
  const timestamp = new Date().toISOString();

  let newContent: string;
  if (!existing) {
    newContent = `# Knowledge Base Evolution Log\n\n- [${timestamp}] ${entry}\n`;
  } else {
    newContent = existing.trim() + `\n- [${timestamp}] ${entry}\n`;
  }

  await writeFile("log", newContent, "Update evolution log");
}
